alert("Hi there. I'm the website, before I let you in I have a couple of basic questions to ask.")
var name = prompt("First up, what's your first name? \(no pun intended\)")
var nameTwo = prompt("Second, what's your last name?")
var age = prompt("Last but not least, what's your age? \(in years please\)")
alert("Thanks " + name + ", that's it for the questions. I'll let you in the website in just a second.")
alert("\(...\)")
var answerOne = prompt("You know, it's weird, I was just reading on the internet about how someone named " + name + " sucks. That's not true is it?")
var answerTwo = prompt("Your answer is " + answerOne + "? Is that really what you meant to say?")
var answerThree = prompt("So, what you really meant to say was " + answerTwo + "? As in " + answerTwo + ", " + name + " sucks?")
var answerFour = prompt("Ok, I think I get it. You're saying " + answerThree + "\ " + name + "\ " + "doesn't suck, but at the same time " + answerTwo + "\ " + name + " doesn't not suck?")
alert("Well, I'm super confused. But in any case it sounds like " + name + " definitely does or doesn't suck.")
alert("I guess the " + name + " I was reading about probably wasn't the same " + name + " as you anyway, huh?")
alert("\(...\)")
alert(nameTwo + "'s a pretty cool last name, I bet people say that all the time though.")
alert("In any case none of this was relevant, I was just curious " + name + ". Sorry about that, I get kind of lonely here sometimes.")
alert("I bet I wouldn't get so lonely if I was " + age + " years old and had a cool last name like " + nameTwo + ".")
alert("\(...\)")
alert("Anyway, I'll let you get on to the website now I guess, thanks for your patience.")
alert("Welcome to the website " + name + "\ " + nameTwo + "!")
console.log("According to you, you're name is " + name + "\ " + nameTwo + " and your age is " + age + ". Is that correct? \(don't answer that\)")
