alert("Hi there.")
var name = prompt("What's your name?")
var answerOne = prompt(name + "? That's so weird, I was just reading on the internet about how someone named " + name + " sucks, is that true?")
var answerTwo = prompt(answerOne + "? Is that really what you meant to say?")
var answerThree = prompt("So, what you really meant to say was " + answerTwo + "? As in " + answerTwo + ", " + name + " sucks?")
var answerFour = prompt("Ok, I think I get it. You're saying " + answerThree + "\ " + name + "\ " + "doesn't suck, but at the same time " + answerTwo + "\ " + name + " doesn't not suck?")
alert("Well, I'm super confused. But in any case it sounds like " + name + " definitely does or doesn't suck.")
alert("I guess the " + name + " I was reading about probably wasn't the same " + name + " as you anyway, huh?")
alert("In any case none of this was relevant, I was just curious. I was just supposed to welcome you to the website.")
alert("Welcome " + name + "!")